#!/bin/bash

# export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
# export YARN_CONF_DIR=$HADOOP_HOME/etc/hadoop

spark-submit --class "cs523.App" --master yarn ./target/final-1.0-jar-with-dependencies.jar kafka

# run agent
# java -cp ./target/final-1.0-jar-with-dependencies.jar cs523.agent.App US pm25 2020-01-01T00:00:00 2020-01-01T00:00:00

# update spark 2 ========================================================

# link reference https://medium.com/@yesilliali/installing-apache-spark-2-x-to-cloudera-quickstart-wm-dd5314e6d9bd

# first step is update jdk 8

# update python 2.7 ---

# yum install centos-release-scl
# yum install scl-utils
# yum install python27
# source /opt/rh/python27/enable

# // check version again
# python --version


# ----

# linkdownload http://spark.apache.org/downloads.html Spark 2.4.4 and Hadoop 2.6

# tar -xvf /home/cloudera/Downloads/spark-2.3.1-bin-hadoop2.6.tgz
# mv spark-2.3.1-bin-hadoop2.6 /usr/local/spark

# vi /etc/default/cloudera-scm-server
# export JAVA_HOME=/usr/java/jdk1.8.0_202

# vi ~/.bash_profile
# export PYSPARK_PYTHON=python
# export SPARK_HOME=/usr/local/spark
# add to PATH $SPARK_HOME/bin

# test run
# /usr/local/spark/bin/pyspark

# =============
# sua 3 file nay tai dong exec
#  vi /usr/bin/pyspark
#  vi /usr/bin/spark-submit
#  vi /usr/bin/spark-shell

# exec /usr/local/spark/bin/pyspark "$@"
# ==============
# ==========================================================================
